import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Suspense } from "react";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages, setRequestLocale} from 'next-intl/server';
import {routing} from '@/i18n/routing';
import { notFound } from 'next/navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/Header";
import ToastProvider from "@/components/ToastProvider";
import { AnalyticsProvider } from "@/components/AnalyticsProvider";
import { PHProvider } from "@/components/PostHogProvider";
import { ActivePersonaProvider } from "@/context/ActivePersonaContext";

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  const {locale} = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 pb-16 sm:pb-0">
        <PHProvider>
          <AnalyticsProvider>
            <NextIntlClientProvider messages={messages}>
              <ActivePersonaProvider>
                <Header />
                <main className="flex-1">
                  {children}
                </main>
                <Suspense fallback={null}>
                  <ToastProvider />
                </Suspense>
              </ActivePersonaProvider>
            </NextIntlClientProvider>
          </AnalyticsProvider>
        </PHProvider>
      </body>
    </html>
  );
}
